layout_spectrum: 0.5860214
color:
  saturation: 0.6816009
  brandStrength: 0.3577618
  lightness: 0.5023894
  rhythmicContrast: 0.4462365
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.6636798
name: Squash Massage & Bodywork
